# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.3
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - php -v
          - apt-get update
          - apt-get install -y unzip git
          - git push https://heroku:c136d546-a957-4268-a303-b91b0974c83b@git.heroku.com/smartestateserver.git HEAD
          - export CACHE_DRIVER=redis
          - export SESSION_DRIVER=redis
          - export DB_CONNECTION=mysql
          - php artisan migrate
